name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Find a directory that serves as a resource pack
        run: find . -mindepth 2 -maxdepth 2 -type f -iname pack.mcmeta | parallel echo {//} > pack.txt

      - name: Creating resource packs from found directories
        run: parallel -a pack.txt --wd {} zip -r "$PWD"/{/}.zip .

      - name: View the resource pack you created.
        run: find . -maxdepth 1 -type f -name "*.zip"

      - uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: action-v${{ github.run_number }}
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}